### PR TITLE
fix: Deprecated / for division #104

### PR DESCRIPTION
**Pull request by lewebsimple**
This fixes the deprecated warning for slash-div.
I used the Sass migrator to make the changes.

### CODE REVIEW

**Comment by SaptakS** [comment]
Seems like this repository is not being updated/maintained.

**Comment by theenoahmason** [comment]
Gentle ping to please merge this extremely simple fix 😁

**Comment by AmirHosseinKarimi** [comment]
Hi. @jonsuh please merge this pull request.

**Comment by ronilaukkarinen** [comment]
Thank you @jonsuh! 👍

**Pull request merged**
