### PR TITLE
Moved variables to `_vars.scss` file

### PR DESCRIPTION
**Pull request by e200**
Hi there! You have a very usefull project and I'm glad to use it!

Today I was trying to calculate the space your hamburger occupy using the project variables, but I stuck on the file importation part.

Instead of import the whole package, I'm importing only the base and the single animation file I want to use.

Since I also need to use the variables on the project, I need to import them too. The problem is that they're inside a file that import the whole project (including the animations that I don't want to load). Since I just want to import the vars, I decide to make this pull request. I think that it makes the code more flexible and improve the separation of concerns.

### CODE REVIEW

**Comment by jonsuh** [comment]
Hi, thank you for the feedback and opening a PR. Hm, that’s an interesting thought—I was considering these variables are more local or private for this library (with the understanding that there aren’t truly “private” variables in SCSS).

Instead, if you have shared variables for your project, I’d suggest setting shared variables for your project, and then change the value of Hamburgers’ variables to the shared variables. For example:

```
$shared-layer-spacing: 4px;


$hamburgers-layer-spacing: $shared-layer-spacing;
@import "hamburgers";


$calculated-layer-spacing: $some-other-variable - $shared-layer-spacing;
.el { width: $calculated-layer-spacing; }
```

That way references to the variable in your project aren’t dependent on Hamburgers, and things won’t break if Hamburgers is ever replace or ripped out.

**Comment by e200** [comment]
@jonsuh, the problem is that I don't need to touch the `hamburgers variables`. I'm not changing anything, I'm using the package spaces, heights, everything, but I need to calculate the space the `hamburger` is consuming.

Right now, my solution was to copy your vars and put them in a file inside my project so I can make the calculations. But this don't sounds good.

**Comment by jonsuh** [comment]
Do you have a repo or sample code you could share with the implementation so I can have a better idea?

**Comment by e200** [comment]
I'll create a Gist. Just a couple of moments.

**Comment by e200** [comment]
Actually I'm not using the vars anymore, I decide to hard code that height calculated by the browser (54px).

**Pull request closed without merging**
